[build]
builder = "nixpacks"
buildCommand = "cd backend && go build -o main ."

[deploy]
startCommand = "cd backend && ./main"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"