[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"
buildContext = "backend"

[deploy]
startCommand = "./main"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"